const { contextBridge, ipcRenderer, webUtils } = require('electron')

const allowedEvents = new Set([
  'log:entry',
  'logs:cleared',
  'task:update',
  'update:state',
  'process:state',
  'process:log',
  'settings:changed',
  'reminder:due',
  'launcher:update-state',
  'launcher:download-progress',
])

contextBridge.exposeInMainWorld('launcher', {
  bootstrap: () => ipcRenderer.invoke('app:bootstrap'),
  getStatus: () => ipcRenderer.invoke('dsh:status'),
  checkUpdate: (options) => ipcRenderer.invoke('dsh:check-update', options),
  install: (target, options) => ipcRenderer.invoke('dsh:install', target, options),
  launch: () => ipcRenderer.invoke('dsh:launch'),
  stop: () => ipcRenderer.invoke('dsh:stop'),
  listPlugins: (profile) => ipcRenderer.invoke('dsh:plugins', profile),
  pluginAction: (profile, action, spec) => ipcRenderer.invoke('dsh:plugin-action', profile, action, spec),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  patchSettings: (patch) => ipcRenderer.invoke('settings:patch', patch),
  getModelConfig: () => ipcRenderer.invoke('dsh:model-config'),
  listSkills: (options) => ipcRenderer.invoke('skills:list', options),
  openSkillDirectory: (id) => ipcRenderer.invoke('skills:open-directory', id),
  openSkillsRoot: () => ipcRenderer.invoke('skills:open-root'),
  getWorkspace: () => ipcRenderer.invoke('workspace:get'),
  listCourses: () => ipcRenderer.invoke('workspace:courses'),
  createCourse: (input) => ipcRenderer.invoke('workspace:course-create', input),
  renameCourse: (id, name) => ipcRenderer.invoke('workspace:course-rename', id, name),
  listBackups: () => ipcRenderer.invoke('workspace:backup-list'),
  createBackup: (label) => ipcRenderer.invoke('workspace:backup-create', label),
  restoreBackup: (fileName) => ipcRenderer.invoke('workspace:backup-restore', fileName),
  checkWorkspaceHealth: () => ipcRenderer.invoke('workspace:health-check'),
  getReminders: () => ipcRenderer.invoke('workspace:reminders'),
  testReminder: () => ipcRenderer.invoke('workspace:reminder-test'),
  exportSnapshot: () => ipcRenderer.invoke('dialog:export-snapshot'),
  importSnapshot: () => ipcRenderer.invoke('dialog:import-snapshot'),
  createAssignment: (input) => ipcRenderer.invoke('workspace:assignment-create', input),
  updateAssignment: (id, patch) => ipcRenderer.invoke('workspace:assignment-update', id, patch),
  deleteAssignment: (id) => ipcRenderer.invoke('workspace:assignment-delete', id),
  createKnowledge: (input) => ipcRenderer.invoke('workspace:knowledge-create', input),
  updateKnowledge: (id, patch) => ipcRenderer.invoke('workspace:knowledge-update', id, patch),
  deleteKnowledge: (id) => ipcRenderer.invoke('workspace:knowledge-delete', id),
  generateKnowledge: (experimentId) =>
    ipcRenderer.invoke('workspace:knowledge-generate', experimentId),
  reviewKnowledge: (id, rating) => ipcRenderer.invoke('workspace:knowledge-review', id, rating),
  importExperiments: (entries) => ipcRenderer.invoke('workspace:experiments-import', entries),
  updateExperiment: (id, patch) => ipcRenderer.invoke('workspace:experiment-update', id, patch),
  renameExperimentGroup: (currentGroup, nextGroup) =>
    ipcRenderer.invoke('workspace:experiment-rename-group', currentGroup, nextGroup),
  deleteExperiment: (id) => ipcRenderer.invoke('workspace:experiment-delete', id),
  importSchedule: (filePath) => ipcRenderer.invoke('schedule:import', filePath),
  createScheduleCourse: (input) => ipcRenderer.invoke('schedule:course-create', input),
  updateScheduleCourse: (id, patch) =>
    ipcRenderer.invoke('schedule:course-update', id, patch),
  deleteScheduleCourse: (id) => ipcRenderer.invoke('schedule:course-delete', id),
  clearSchedule: () => ipcRenderer.invoke('schedule:clear'),
  copyText: (value) => ipcRenderer.invoke('clipboard:write', value),
  stageDroppedFile: (payload) => ipcRenderer.invoke('file:stage-drop', payload),
  chooseDshHome: () => ipcRenderer.invoke('dialog:choose-dsh-home'),
  chooseExperimentDir: () => ipcRenderer.invoke('dialog:choose-experiment-dir'),
  chooseExperimentFiles: () => ipcRenderer.invoke('dialog:choose-experiment-files'),
  chooseExperimentPdfs: () => ipcRenderer.invoke('dialog:choose-experiment-pdfs'),
  chooseScheduleFile: () => ipcRenderer.invoke('dialog:choose-schedule-file'),
  openExperimentFile: (id) => ipcRenderer.invoke('experiments:open-file', id),
  revealExperimentFile: (id) => ipcRenderer.invoke('experiments:reveal-file', id),
  openExperimentDirectory: (group) => ipcRenderer.invoke('experiments:open-directory', group),
  revealScheduleSource: () => ipcRenderer.invoke('schedule:reveal-source'),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  openPath: (target) => ipcRenderer.invoke('path:open', target),
  openExternal: (url) => ipcRenderer.invoke('external:open', url),
  clearLogs: () => ipcRenderer.invoke('logs:clear'),
  checkLauncherUpdate: () => ipcRenderer.invoke('launcher:check-update'),
  downloadLauncherUpdate: (asset) => ipcRenderer.invoke('launcher:download-update', asset),
  on: (channel, callback) => {
    if (!allowedEvents.has(channel)) throw new Error(`不允许监听事件：${channel}`)
    const listener = (_event, payload) => callback(payload)
    ipcRenderer.on(channel, listener)
    return () => ipcRenderer.removeListener(channel, listener)
  },
})
